name: Test

on:
  push:
    branches-ignore:
      - main # tests will be launched by workflow_call from the "Release" workflow
  pull_request:
    types: [ opened, reopened ]
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        operating_system: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false # run tests on other operating systems even if one fails

    runs-on: ${{ matrix.operating_system }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
        
